### ISSUE TITLE
Meshtastic missing from protocol list when adding Pidgin account

### ISSUE THREAD

**Issue by Nealtron** [dadecoza/pidgin-meshtastic#2]
Saw your project on Reddit and figured I'd give it a try.  Unfortunately, I cannot add any of my devices to pidgin because Meshtastic is not available from the protocol pull-down. My workstation is running Windows 11 23H2, and I performed a fresh install of Pidgin 2.14.13. 

![image](https://github.com/user-attachments/assets/1898bf80-be98-49d0-b5c5-2b5565b24a54)

![image](https://github.com/user-attachments/assets/53a07d88-05d4-4087-8495-94cc19b35254)

I originally installed the Meshtastic plugin via the [pidgin-meshtastic-0.1.0-alpha.exe installer](https://github.com/dadecoza/pidgin-meshtastic/releases/download/v0.1.0-alpha/pidgin-meshtastic-0.1.0-alpha.exe). 

I also downloaded the latest [Nightly](https://github.com/dadecoza/pidgin-meshtastic/releases/tag/nightly-66dfae77819ff88e6470ec672302e2d24c5173a4), and copied the dll to the plugins folder and the pixmaps folder into the Pidgin directory.

Finally, I also tried following the official Pidgin documentation regarding installation of plugins, and copied the dll file to %appdata%\Roaming\.purple\plugins, but still no change.

**Comment by dadecoza** [comment]
Hi Nealtron!

Thanks for the feedback :) You are indeed correct! The DLL from the nightly builds is also not working for me ... we are investigating and will update the issue when it is fixed.

For now can you please try https://dade.co.za/pidgin-meshtastic-0.1.3-alpha.exe ?

**Comment by Nealtron** [comment]
Issue resolved! Alpha 13 did the trick. I've added my 2 mesh nodes, and I'll start testing. Thank you!

![image](https://github.com/user-attachments/assets/b7fbf9e8-f6fe-4ccb-8ee7-9bf7e2b6afd1)

**Comment by dadecoza** [comment]
Great  :)

The .DLL and installer in the nightly builds/releases are also now fixed.

Thanks for reporting the issue.
