### ISSUE TITLE
Typo in "Seen" when hovering over a contact

### ISSUE THREAD

**Issue by theanswriz42** [dadecoza/pidgin-meshtastic#4]
Super minor, but there's a typo in the "Seen" field when you hover the cursor over a user. It should say "minutes" however it currently says "miutes". I've also gone ahead and pasted a screenshot. 

![image](https://github.com/user-attachments/assets/a65d3cc4-223c-4753-9f5d-418942414c26)

**Comment by ashleycawley** [comment]
Nice spot!

I know its an incredibly tiny change but I'm new to contributing to others projects, so getting used to the workflow, here goes: I think I've [submitted a change](https://github.com/dadecoza/pidgin-meshtastic/pull/5) to fix that!

**Comment by dadecoza** [comment]
Thanks @ashleycawley
